os: linux
dist: focal
language: cpp
compiler: 
- gcc
cache:
    directories:
        - "/var/cache/apt/archives/*.deb"
        - ".cross_compiler/"
before_install:
    - sudo apt-get update
    - make setup_echfs_utils
    - cd echfs/
    - sudo make install
    - cd ..
    - sudo apt-get install -y parted
    - sudo apt-get install -y nasm grub-pc-bin binutils mtools build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo
script:
    - "./make_cross_compiler.sh"
    - make disk
